import { config } from ".";
import { getToken } from "./auth";
import { axiosMasterLogger } from "axios-master";
import { AxiosResponse } from "axios";
/* -----------------------------
 * Enums
 * ----------------------------- */

export const genders = ["MEN", "WOMEN"] as const;
export type Gender = (typeof genders)[number];

/* -----------------------------
 * Types
 * ----------------------------- */

export interface UserEmailItem {
  email: string;
  verified: boolean;
  primary: boolean;
}

export interface UserPhoneItem {
  number: string;
  verified: boolean;
  primary: boolean;
}

export interface UserAuthProfiles {
  facebook_id?: string | null;
  google_id?: string | null;
  steam_id?: string | null;
  apple_id?: string | null;
  twitter_id?: string | null;
  monpay_id?: string | null;
  toki_id?: string | null;
  social_id?: string | null;
  hipay_id?: string | null;
  digi_id?: string | null;
}

export interface UserPreferences {
  language: string;
  notifications: boolean;
}

export interface UserStatus {
  is_active: boolean;
  is_banned: boolean;
  verified: boolean;
}

export interface UserSecurity {
  password_hash: string;
  two_factor_enabled: boolean;
  last_password_change: Date | null;
}

export interface UserVerifyInfo {
  first_name: string;
  last_name: string;
  born_date: Date | null;
  national_id: string;
}

export interface UserAppItem {
  app_name: string;
  app_id: string;
  device_id: string;
}

export interface UserWalletItem {
  key_id: string;
  wallet_id: string;
  wallet_key: string;
  wallet_type: string;
  wallet_name: string;
  role: string[];
}

type UserT = {
  user_id: number;
  user_name: string;
  nick_name: string;
  exp: number;

  primary_email?: string | null;
  primary_phone?: string | null;

  emails: UserEmailItem[];
  phone_numbers: UserPhoneItem[];

  auth_profiles: UserAuthProfiles;

  profile_image_url: string;
  date_of_birth: Date | null;
  gender?: Gender;

  sign_up_date: Date | null;
  last_login: Date | null;

  wallets: UserWalletItem[];

  preferences: UserPreferences;
  status: UserStatus;
  security: UserSecurity;

  verify_info: UserVerifyInfo;

  dynamic_info: Record<string, any>;
  apps: UserAppItem[];

  // STANDARD
  search_string?: string;
  delFlg?: boolean;
  order_index?: number;
};
type ApiResponse<T> = {
  code: string;
  success: boolean;
  message: string;
  token?: string;
  data: T;
};

type MerchantT = {
  _id?: string;
  user_id: number;
  user_name?: string;
  phone_number?: string; // Stored as string to prevent issues with leading zeros
  user_role?: "merchant" | "sub-merchant";
  avatar?: string;
  authority?: string[];
  user_email?: string;
  password?: string;
  show_router?: string[];
  show_id?: string[];
  merchant: {
    toki_id: string;
    hipay: string;
  };
  wallet_id?: string;
  wallet_key?: string;
  delFlg?: boolean;
  createdAt?: Date;
  updatedAt?: Date;
};
type AdminT = {
  _id?: string;
  user_id?: number;
  user_name?: string;
  phone_number?: number;
  user_role?: "admin" | "sub-admin" | "super-admin";
  avatar?: string;
  authority?: string[];
  user_email?: string;
  password?: string;
  show_router?: string[];
  show_id?: string[];
  delFlg?: boolean;
  createdAt?: Date; // Automatically generated by Mongoose with timestamps
  updatedAt?: Date; // Automatically generated by Mongoose with timestamps
};
type ClientT = {
  _id?: string;
  user_id?: number;
  user_name?: string;
  phone_number?: number;
  user_role?: "crm" | "sub-crm";
  avatar?: string;
  authority?: string[];
  user_email?: string;
  password?: string;
  show_router?: string[];
  show_id?: string[];
  RefundFun?: boolean;
  delFlg?: boolean;
  createdAt?: Date;
  updatedAt?: Date;
};
type CrmT = {
  _id?: string;
  user_id?: number;
  user_name?: string;
  phone_number?: number;
  user_role?: "crm" | "sub-crm";
  avatar?: string;
  authority?: string[];
  user_email?: string;
  password?: string;
  show_router?: string[];
  show_id?: string[];
  RefundFun?: boolean;
  delFlg?: boolean;
  createdAt?: Date;
  updatedAt?: Date;
};
export const USER = async (
  body: UserT
): Promise<{ success: boolean; data: UserT[]; message: string }> => {
  try {
    const result: ApiResponse<[]> = await axiosMasterLogger(
      {
        method: "POST",
        maxBodyLength: Infinity,
        url: `${config.hosts.MAIN}/main/v1/auth/support/find/user`,
        headers: {
          Accept: "application/json",
          "Content-Type": "application/json",
          Authorization: `Bearer ${config.token}`
        },
        data: body
      },
      {
        name: "support/find/user",
        timeout: 20000,
        retryFunction: getToken,
        shouldRetry: true,
        shouldRetryStatus: [401, 400],
        logger(data) {
          if (config.logger) {
            console.log({
              time: data.json.time,
              request: data.json.request,
              response: `${data.json.response}`,
              responseBody: data.json.responseBody,
              statusCode: data.json.statusCode
            });
          }
        }
      }
    );

    return { success: true, data: result.data, message: result.message };
  } catch (error) {
    const axiosError = error as AxiosResponse<ApiResponse<{}>>;
    if (axiosError.data) {
      console.log(axiosError.data);
    } else {
      console.error("Request Failed:", axiosError);
    }
    return {
      success: false,
      data: [],
      message: axiosError.data?.message || ""
    };
  }
};
export const MERCHANT = async (
  body: MerchantT
): Promise<{ success: boolean; data: MerchantT[]; message: string }> => {
  try {
    const result: ApiResponse<[]> = await axiosMasterLogger(
      {
        method: "POST",
        maxBodyLength: Infinity,
        url: `${config.hosts.MAIN}/main/v1/auth/support/find/merchant`,
        headers: {
          Accept: "application/json",
          "Content-Type": "application/json",
          Authorization: `Bearer ${config.token}`
        },
        data: body
      },
      {
        name: "support/find/merchant",
        timeout: 20000,
        retryFunction: getToken,
        shouldRetry: true,
        shouldRetryStatus: [401, 400],
        logger(data) {
          if (config.logger) {
            console.log({
              time: data.json.time,
              request: data.json.request,
              response: `${data.json.response}`,
              responseBody: data.json.responseBody,
              statusCode: data.json.statusCode
            });
          }
        }
      }
    );

    return { success: true, data: result.data, message: result.message };
  } catch (error) {
    const axiosError = error as AxiosResponse<ApiResponse<{}>>;
    if (axiosError.data) {
      console.log(axiosError.data);
    } else {
      console.error("Request Failed:", axiosError);
    }
    return {
      success: false,
      data: [],
      message: axiosError.data?.message || ""
    };
  }
};
export const ADMIN = async (
  body: AdminT
): Promise<{ success: boolean; data: AdminT[]; message: string }> => {
  try {
    const result: ApiResponse<[]> = await axiosMasterLogger(
      {
        method: "POST",
        maxBodyLength: Infinity,
        url: `${config.hosts.MAIN}/main/v1/auth/support/find/admin`,
        headers: {
          Accept: "application/json",
          "Content-Type": "application/json",
          Authorization: `Bearer ${config.token}`
        },
        data: body
      },
      {
        name: "support/find/admin",
        timeout: 20000,
        retryFunction: getToken,
        shouldRetry: true,
        shouldRetryStatus: [401, 400],
        logger(data) {
          if (config.logger) {
            console.log({
              time: data.json.time,
              request: data.json.request,
              response: `${data.json.response}`,
              responseBody: data.json.responseBody,
              statusCode: data.json.statusCode
            });
          }
        }
      }
    );

    return { success: true, data: result.data, message: result.message };
  } catch (error) {
    const axiosError = error as AxiosResponse<ApiResponse<{}>>;
    if (axiosError.data) {
      console.log(axiosError.data);
    } else {
      console.error("Request Failed:", axiosError);
    }
    return {
      success: false,
      data: [],
      message: axiosError.data?.message || ""
    };
  }
};
export const CLIENT = async (
  body: ClientT
): Promise<{ success: boolean; data: ClientT[]; message: string }> => {
  try {
    const result: ApiResponse<[]> = await axiosMasterLogger(
      {
        method: "POST",
        maxBodyLength: Infinity,
        url: `${config.hosts.MAIN}/main/v1/auth/support/find/client`,
        headers: {
          Accept: "application/json",
          "Content-Type": "application/json",
          Authorization: `Bearer ${config.token}`
        },
        data: body
      },
      {
        name: "support/find/client",
        timeout: 20000,
        retryFunction: getToken,
        shouldRetry: true,
        shouldRetryStatus: [401, 400],
        logger(data) {
          if (config.logger) {
            console.log({
              time: data.json.time,
              request: data.json.request,
              response: `${data.json.response}`,
              responseBody: data.json.responseBody,
              statusCode: data.json.statusCode
            });
          }
        }
      }
    );

    return { success: true, data: result.data, message: result.message };
  } catch (error) {
    const axiosError = error as AxiosResponse<ApiResponse<{}>>;
    if (axiosError.data) {
      console.log(axiosError.data);
    } else {
      console.error("Request Failed:", axiosError);
    }
    return {
      success: false,
      data: [],
      message: axiosError.data?.message || ""
    };
  }
};
export const CRM = async (
  body: CrmT
): Promise<{ success: boolean; data: CrmT[]; message: string }> => {
  try {
    const result: ApiResponse<[]> = await axiosMasterLogger(
      {
        method: "POST",
        maxBodyLength: Infinity,
        url: `${config.hosts.MAIN}/main/v1/auth/support/find/crm`,
        headers: {
          Accept: "application/json",
          "Content-Type": "application/json",
          Authorization: `Bearer ${config.token}`
        },
        data: body
      },
      {
        name: "support/find/crm",
        timeout: 20000,
        retryFunction: getToken,
        shouldRetry: true,
        shouldRetryStatus: [401, 400],
        logger(data) {
          if (config.logger) {
            console.log({
              time: data.json.time,
              request: data.json.request,
              response: `${data.json.response}`,
              responseBody: data.json.responseBody,
              statusCode: data.json.statusCode
            });
          }
        }
      }
    );

    return { success: true, data: result.data, message: result.message };
  } catch (error) {
    const axiosError = error as AxiosResponse<ApiResponse<{}>>;
    if (axiosError.data) {
      console.log(axiosError.data);
    } else {
      console.error("Request Failed:", axiosError);
    }
    return {
      success: false,
      data: [],
      message: axiosError.data?.message || ""
    };
  }
};
export default { USER, MERCHANT, ADMIN, CLIENT, CRM };
